[package]
name = "art-plugin-loader"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0"
goblin = "0.9"
xz2 = { version = "0.1", features = ["static"] }

[build-dependencies]
cc = "1.2"
bindgen = "0.71"
